#!/usr/bin/env python3
"""Generate TypeScript types from Pydantic models.

This script is THE ENFORCEMENT MECHANISM for the Pydantic-first architecture.
Run this after ANY change to server/models/tribrid_config_model.py.

Usage:
    uv run scripts/generate_types.py

The generated file (web/src/types/generated.ts) should NEVER be edited by hand.
All TypeScript types for API data MUST be imported from generated.ts.
"""
import subprocess
import sys
from pathlib import Path


def main() -> None:
    """Run pydantic2ts to generate TypeScript types."""
    print("=" * 60)
    print("GENERATING TYPESCRIPT TYPES FROM PYDANTIC MODELS")
    print("=" * 60)

    project_root = Path(__file__).parent.parent
    output_path = project_root / "web" / "src" / "types" / "generated.ts"

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"\nSource: server.models.tribrid_config_model")
    print(f"Output: {output_path}\n")

    cmd = [
        sys.executable,
        "-m",
        "pydantic2ts",
        "--module",
        "server.models.tribrid_config_model",
        "--output",
        str(output_path),
    ]

    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=project_root, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"\nERROR: Type generation failed!")
        print(f"STDERR: {result.stderr}")
        print(f"STDOUT: {result.stdout}")
        sys.exit(1)

    # Add header comment to generated file
    content = output_path.read_text()
    header = '''/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * Generated from: server/models/tribrid_config_model.py
 * Generated by: scripts/generate_types.py
 * 
 * To regenerate: uv run scripts/generate_types.py
 * 
 * ALL TypeScript types for API data MUST be imported from this file.
 * Hand-writing interfaces that should come from Pydantic is FORBIDDEN.
 */

'''
    output_path.write_text(header + content)

    print("\nSUCCESS! Types generated.")
    print(f"Output: {output_path}")
    print(f"Size: {output_path.stat().st_size} bytes")

    # Count interfaces
    interface_count = content.count("export interface")
    type_count = content.count("export type")
    print(f"Interfaces: {interface_count}")
    print(f"Types: {type_count}")
    print()
    print("Remember: Import from 'types/generated' not hand-written interfaces!")


if __name__ == "__main__":
    main()
